default:
  JAGS_DATA:
    seed: 69 #set NULL for random seed
    chains: 3
    iterations: 500
    burn_in: 100
    thin: 1
    save_parameters:
      - "pi"
      - "p"
      - "eta"
  DATA_META:
    id_column_name: "Sample_Name"
    training_column_name: "training"
    class_column_prefix: "CL_"
    feature_column_prefix: "FE_"
  ANALYSIS:
    groups:
      human:
        - "_human_"
      meat:
        - "_chicken_"
        - "_pork_"
        - "_beef_"
    plots:
      save_plots: TRUE
      plot_format: "png" #only png supported
  OPTIONS:
    delete_temp_files: FALSE