#!/usr/bin/env bash
#SBATCH --job-name=HABITAT_initator
#SBATCH --output=HABITAT_initator.out
#SBATCH --error=HABITAT_initator.err
#SBATCH --time=12:00:00
#SBATCH --partition=cpu
#STATCH --cpus-per-task=1
#SBATCH --mem=4G


usage() {
    Rscript "$SCRIPT_DIR/run_bayesian.R" --help
}

while getopts "h" opt; do
  case $opt in
    h)usage; exit 0 ;;
    *)usage; exit 1 ;;
  esac
done

